"use server";

import { mastra } from "@/mastra";
import { convertMessages } from "@mastra/core/agent"

const myAgent = mastra.getAgent("RiskAssessmentAgent");

export async function Threads({ threadId = "" }) {

    console.log("GET request received", threadId);

    if (!threadId) {
        return convertMessages([]).to('AIV5.UI');
    }

    const memory = await myAgent.getMemory()
    const result = await memory?.query({
        threadId,
    });

    const messages = convertMessages(result?.uiMessages || []).to('AIV5.UI');

    return messages;
}

export async function CreateThread({ resourceId = "demo" }) {

    const memory = await myAgent.getMemory()

    const thread = await memory?.createThread({
        resourceId
    })

    return thread;
}

export async function CreateThreadWithMessage({ message, resourceId = "demo" }: {
    message: string;
    resourceId?: string;
}) {
    console.log("Creating new thread for patient case");

    const memory = await myAgent.getMemory();

    // Create a new thread without a title - it will be auto-generated by the agent
    // based on the first message (configured in memory options with generateTitle)
    const thread = await memory?.createThread({
        resourceId,
    });

    if (!thread?.id) {
        throw new Error("Failed to create thread");
    }

    console.log("Thread created:", thread.id);

    // The title will be auto-generated by Mastra after the first message is sent
    // This happens in the conversation component when sendMessage is called

    return {
        threadId: thread.id
    };
}

export async function deleteThread(id: string) {

    try {

        const memory = await myAgent.getMemory();
        const thread = await memory?.deleteThread(id)

        return thread
    } catch (err) {
        console.log(err)
    }

}